version: '3.4'

volumes:
  shared_volume:

services:

  scrapper:
    image: 1062b2cd38ae
    volumes:
      - "shared_volume:/var/shared_volume"

  postgres:
    image: 6639a985a757
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_DB: ${POSTGRES_DB:-docker}
    depends_on:
      - scrapper
    volumes:
      - "shared_volume:/var/shared_volume"

 